export { default as IconCheck } from './IconCheck.jsx'
export { default as IconInstagram } from './IconInstagram.jsx'
export { default as IconFacebook } from './IconFacebook.jsx'
export { default as IconArrowRight } from './IconArrowRight.jsx'
export { default as IconArrowLeft } from './IconArrowLeft.jsx'
export { default as IconLinkedin } from './IconLinkedin.jsx'
export { default as IconTwitter } from './IconTwitter.jsx'
export { default as IconShare } from './IconShare.jsx'
